version: '3.7'

services:
  partner:
    build: .
    restart: always
    container_name: partner-service
    ports:
      - 8182:8080
    working_dir: /app
    depends_on:
      - mongodb
    networks:
      - partner-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: partner
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: partner_service
    ports:
      - 27017:27017
    volumes:
      - ./resources/db/V1__init_db.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - partner-network
    command: ["--bind_ip_all"]

networks:
  partner-network:
    driver: bridge